version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chacurbanos-back
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    entrypoint: npm start