name: Build, Test, and Deploy

on:
    push:
        branches: ['develop', 'main']
    pull_request:
        branches: ['develop', 'main']

jobs:
    build-test-deploy:
        name: Build, Test, and Deploy with Docker
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
        
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker Image
              run: |
                  docker build -t chacurbanos-back .

            - name: Start Server
              run: npm start &
                  
            - name: Wait for Server to Start
              run: sleep 10

            - name: Run Tests
              run: npm run test

- name: Upgrade AWS CLI version and setup lightsailctl
      run: |
          aws --version
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          which aws
          aws --version
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

- name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: ${{ secrets.AWS_ARN_OICN_ACCESS }}
          role-session-name: Github
          aws-region: us-east-1

- name: Deploy to Lightsail
      run: lightsailctl push -s <fast-delivery-chacurbanos> -i chacurbanos-back

- name: Login to Docker Hub
      uses: docker/login-action@v2
       with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

- name: Build and Push Docker Image to Docker Hub
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  run: |
    docker build -t tute22/chacurbanos-back:latest .
    docker push tute22/chacurbanos-back:latest

    
- name: Pull Docker Image from Docker Hub
  run: docker pull tute22/chacurbanos-back:latest

- name: Tag Docker Image for Lightsail
  run: docker tag tute22/chacurbanos-back:latest ${{vars.LIGHTSAIL_IMAGE}}:${{ github.sha }}

- name: Push Docker Image to Lightsail
  run: aws lightsail push-container-image --service-name ${{ SERVICE_NAME }} --image ${{ LIGHTSAIL_IMAGE }}:${{ github.sha }} --region us-east-1 --label git-push

- name: Save updated LIGHTSAIL_IMAGE_TAG 
  run: |
    echo "LIGHTSAIL_DOCKER_IMAGE=$(aws lightsail get-container-images --service-name ${{ SERVICE_NAME }} --region us-east-1 | jq -r .containerImages[0].image)"  >> $GITHUB_ENV

- name: Start New Deployment to Light Sail
  run: |
    aws lightsail create-container-service-deployment --region us-east-1 --service-name ${{ SERVICE_NAME }} --output yaml --containers "{ \"${{ SERVICE_NAME }}\": { \"image\": \"$LIGHTSAIL_DOCKER_IMAGE\", \"environment\": { \"VERSION\": \"${{ github.run_number }}\" }, \"ports\": { \"8000\": \"HTTP\" } } }" --public-endpoint "{ \"containerName\": \"${{ SERVICE_NAME }}\", \"containerPort\": 8000, \"healthCheck\": { \"path\": \"/healthcheck/liveness\", \"intervalSeconds\": 10 } }"


name: Build, Test, and Deploy

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Start Server
        run: npm start &

      - name: Wait for Server to Start
        run: sleep 10

      - name: Run Tests
        run: npm run test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t tute22/chacurbanos-back:latest .
          docker push tute22/chacurbanos-back:latest

  deploy-to-lightsail:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARN_OICN_ACCESS }}
          role-session-name: GithubActions
          aws-region: us-east-1

      - name: Deploy to Lightsail
        run: |
          aws lightsail push-container-image --service-name fast-delivery-chacurbanos --label fast-delivery-chacurbanos --image tute22/chacurbanos-back:latest